// <auto-generated />
using System;
using System.Collections.Generic;
using Engine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace engine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260924202100_SignalOutcomes")]
    partial class SignalOutcomes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trading")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Engine.Application.Persistence.DecisionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvailableRiskBudgetUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("available_risk_budget_usd");

                    b.Property<double?>("Conviction")
                        .HasColumnType("double precision")
                        .HasColumnName("conviction");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<decimal?>("ExistingAveragePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("existing_average_price");

                    b.Property<decimal?>("ExistingQuantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("existing_quantity");

                    b.Property<int?>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.PrimitiveCollection<string[]>("KeyRisks")
                        .IsRequired()
                        .HasColumnType("varchar(300)[]")
                        .HasColumnName("key_risks");

                    b.Property<decimal>("MaxPositionPct")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("max_position_pct");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<string>("OutcomeReason")
                        .HasColumnType("text")
                        .HasColumnName("outcome_reason");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<DateTimeOffset?>("QuoteAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_as_of");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReferenceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("reference_currency")
                        .IsFixedLength();

                    b.Property<decimal?>("ReferencePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("reference_price");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int?>("Revisions")
                        .HasColumnType("integer")
                        .HasColumnName("revisions");

                    b.Property<string>("Stance")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("stance");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("team_version");

                    b.Property<string>("Thesis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("thesis");

                    b.HasKey("Id")
                        .HasName("pk_decisions");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_decisions_correlation_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_decisions_order_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_decisions_portfolio_id");

                    b.HasIndex("Symbol", "RequestedAt")
                        .HasDatabaseName("ix_decisions_symbol_requested_at");

                    b.HasIndex("TeamVersion", "Outcome")
                        .HasDatabaseName("ix_decisions_team_version_outcome");

                    b.ToTable("decisions", "trading");
                });

            modelBuilder.Entity("Engine.Application.Persistence.SignalOutcomeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BenchmarkReturn")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("benchmark_return");

                    b.Property<string>("BenchmarkSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("benchmark_symbol");

                    b.Property<decimal?>("CostFraction")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost_fraction");

                    b.Property<long>("DecisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("decision_id");

                    b.Property<decimal?>("ExcessReturn")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("excess_return");

                    b.Property<bool?>("Hit")
                        .HasColumnType("boolean")
                        .HasColumnName("hit");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<string>("HorizonUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("horizon_unit");

                    b.Property<decimal?>("InstrumentReturn")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("instrument_return");

                    b.Property<DateOnly?>("MeasuredOn")
                        .HasColumnType("date")
                        .HasColumnName("measured_on");

                    b.Property<decimal?>("MeasuredPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("measured_price");

                    b.Property<decimal?>("NetEdge")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("net_edge");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_signal_outcomes");

                    b.HasIndex("DecisionId", "HorizonUnit", "HorizonDays")
                        .IsUnique()
                        .HasDatabaseName("ix_signal_outcomes_decision_id_horizon_unit_horizon_days");

                    b.ToTable("signal_outcomes", "trading");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Engine.Domain.Aggregates.Portfolio.Order.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_orders_portfolio_id");

                    b.ToTable("orders", "trading");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CashBalance", "Engine.Domain.Aggregates.Portfolio.Portfolio.CashBalance#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("cash_balance_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("cash_balance_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.ToTable("portfolios", "trading");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Position", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AveragePurchasePrice", "Engine.Domain.Aggregates.Portfolio.Position.AveragePurchasePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("average_purchase_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("average_purchase_price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("PortfolioId", "Ticker")
                        .HasName("pk_positions");

                    b.ToTable("positions", "trading");
                });

            modelBuilder.Entity("Engine.Application.Persistence.DecisionRecord", b =>
                {
                    b.HasOne("Engine.Domain.Aggregates.Portfolio.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_decisions_orders_order_id");

                    b.HasOne("Engine.Domain.Aggregates.Portfolio.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_portfolios_portfolio_id");
                });

            modelBuilder.Entity("Engine.Application.Persistence.SignalOutcomeRecord", b =>
                {
                    b.HasOne("Engine.Application.Persistence.DecisionRecord", null)
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_signal_outcomes_decisions_decision_id");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Order", b =>
                {
                    b.HasOne("Engine.Domain.Aggregates.Portfolio.Portfolio", null)
                        .WithMany("NewOrders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_portfolios_portfolio_id");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Position", b =>
                {
                    b.HasOne("Engine.Domain.Aggregates.Portfolio.Portfolio", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_portfolios_portfolio_id");
                });

            modelBuilder.Entity("Engine.Domain.Aggregates.Portfolio.Portfolio", b =>
                {
                    b.Navigation("NewOrders");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
